language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - if [ $TRAVIS_PYTHON_VERSION == "2.7" -o $TRAVIS_PYTHON_VERSION == "3.4" ]; then pip install pyparsing==2.4.7; fi
  - if [ $TRAVIS_PYTHON_VERSION == "3.4" ]; then pip install PyYAML==5.2; fi
# develop seems to be required by travis since 02/2013
  - python setup.py build develop
  # newer versions of docutils dropped support for Python 3.4
  - if [ $TRAVIS_PYTHON_VERSION == "3.4" ]; then pip install docutils==0.15.2; fi
  - pip install PyYAML argparse catkin_pkg rospkg setuptools
  - pip install nose coverage mock
# command to run tests
script:
  - nosetests --with-xunit test
notifications:
  email: false
