#!/usr/bin/env python3

import sys

from rosdistro.cli.rosdistro_reformat import main

if __name__ == '__main__':
    print('The rosdistro_reformat script is deprecated. Use python3 '
          "-m 'rosdistro.cli.rosdistro_reformat' instead.\n",
          file=sys.stderr)
    sys.exit(main())
