#!/usr/bin/env python

import rosdistro
import optparse
import sys

def main():
    parser = optparse.OptionParser()
    parser.add_option("--cache", action="store", default=None)
    (options, args) = parser.parse_args()

    if len(args) != 1:
        print "Usage: %s ros_distro"%sys.argv[0]
        return

    # touch everything to create the new cache
    distro  = rosdistro.RosDistro(sys.argv[1], options.cache)
    distro._build_full_dependency_tree()

    print "Cache written to %s"%(distro.depends_file.local_url)

if __name__ == "__main__":
    main()
