#!/usr/bin/env python3

import sys

from rosdistro.cli.rosdistro_freeze_source import main

if __name__ == '__main__':
    print('The rosdistro_freeze_source script is deprecated. Use python3 '
          "-m 'rosdistro.cli.rosdistro_freeze_source' instead.\n",
          file=sys.stderr)
    sys.exit(main())
